version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.10.0

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run lint
      - run: npm run build

workflows:
  version: 2
  build-workflow:
    jobs:
    - test
