version: 2
anchors:
  - restore_cache: &restore_cache
    keys:
    - v1-dependencies-{{ checksum "package.json" }}
    - v1-dependencies-

  - run: &setup
    - npm install

  - save_cache: &save_cache
      paths:
      - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    docker:
      - image: circleci/node:10.10.0

    working_directory: ~/repo

    steps:
      - *restore_cache
      - *setup
      - *save_cache
      - run: npm run test

  lint:
    docker:
      - image: circleci/node:10.10.0

    working_directory: ~/repo

    steps:
      - *restore_cache
      - *setup
      - *save_cache
      - run: npm run lint

  build:
    docker:
      - image: circleci/node:10.10.0

    working_directory: ~/repo

    steps:
      - *restore_cache
      - *setup
      - *save_cache
      - run: npm run build

workflows:
  version: 2
  build-workflow:
    jobs:
      - lint
      - test
